#!/usr/bin/env ruby
require './lib/cli'

path = ARGV[1]
sensitive_keys_path = ARGV[0]

begin
    puts "Running CLI Scrub Tool"
    cli_tool = CLI.new(path, sensitive_keys_path)
    cli_tool.run
rescue Errno::ENOENT
    p "File(s) not found in path [#{path}] or [#{sensitive_keys_path}]"
rescue ArgumentError
    p "There was something wrong with the files inputted."
end



puts "Done running CLI Scrub Tool"